### ISSUE TITLE
Input must be >=2-d

### ISSUE THREAD

**Issue by moyan007** [bobo0810/PytorchNetHub#4]
Hello sir, when I tried to run your demo, I met several obstacles. Can you help me with the error of that? Thanks a lot

Traceback (most recent call last):
  File "main.py", line 255, in <module>
    train()
  File "main.py", line 102, in train
    for i, (images, target) in enumerate(train_loader):
  File "/home/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/Downloads/project/AnnotatedNetworkModelGit/Yolov1_pytorch/data/dataset.py", line 78, in __getitem__
    img, boxes = self.random_flip(img, boxes)
  File "/home/Downloads/project/AnnotatedNetworkModelGit/Yolov1_pytorch/data/dataset.py", line 287, in random_flip
    im_lr = np.fliplr(im).copy()
  File "/home/anaconda3/lib/python3.6/site-packages/numpy/lib/twodim_base.py", line 82, in fliplr
    raise ValueError("Input must be >= 2-d.")
ValueError: Input must be >= 2-d.

It's occured in yolov1.

**Comment by bobo0810** [comment]
@moyan007 
The error message has explained the problem, np.fliplr is not used correctly, you should try debug mode for further understanding.
`im_lr = np.fliplr(im).copy()`
